export default {
  LOGIN: "Login",
  SIGN_UP: "SignUp",
  ONBOARDING: "Onboarding",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  HOME: "Home",
  HOME_STACK: "HomeStack",
  HOME_DRAWER: "HomeDrawer",
  HOME_BOTTOM_TABS: "HomeBottomTabs",
  CLASSES: "Classes",
  EXAMS: "Exams",
  RESULTS: "Results",
  CLASS: "Class",
  EXAM: "Exam",
  RESULT: "Result",
  SETTINGS: "Settings",
  ABOUT: "About",
  CONTACT: "Contact",
  EDIT_CLASS: "EditClass",
  ADD_CLASS: "AddClass",
}