export default {
  app_name: 'Optik Okuyucu',
  app_name_upper: 'OPTİK OKUYUCU',
  onboarding: {
    title: 'OPTİK OKUYUCU',
    welcome: 'Hoş Geldiniz!',
    slogan: 'Yeni Nesil Optik Okuyucuyu Keşfedin.',
    login: 'Giriş Yap',
    sign_up: 'Kayıt Ol',
    or: 'veya',
  },
  login: {
    login: 'Giriş Yap',
    email: 'E-posta',
    password: 'Şifre',
    forgot_password: 'Şifremi Unuttum',
    email_required: 'E-posta adresinizi giriniz.',
    password_required: 'Şifrenizi giriniz.',
    login_failed: 'E-posta adresiniz veya şifreniz hatalı.',
  },
  sign_up: {
    sign_up: 'Kayıt Ol',
    full_name: 'Ad Soyad',
    email: 'E-posta',
    password: 'Şifre',
    fill_required_fields: 'Lütfen tüm alanları doldurunuz.',
    by_signing_up: 'Kayıt olarak, ',
    terms_of_service: 'kullanım şartlarını ',
    and: 've ',
    privacy_policy: 'gizlilik politikasını',
    accept: ' okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.',
  },
  about: {
    about: 'Hakkında',
    version: 'Versiyon',
    version_number: '1.0.0',

  },
  errors: {
    email_already_in_use: 'Bu e-posta adresi zaten kayıtlı.',
    weak_password: 'Şifreniz en az 6 karakter uzunluğunda olmalıdır.',
    invalid_email: 'Lütfen geçerli bir e-posta adresi giriniz.',
    operation_not_allowed: 'Bu işlem şu anda gerçekleştirilemiyor.',
    unknown_error: 'Bilinmeyen bir hata oluştu.',
    user_not_found: 'Bu e-posta adresi ile kayıtlı bir kullanıcı bulunamadı.',
    wrong_password: 'Şifreniz hatalı.',
  },
  home: {
    home: 'Ana Sayfa',
    welcome: 'Hoş geldiniz',
    slogan: 'Yeni Nesil Optik Okuyucuyu Keşfedin.',
    scan: 'Tarama Yap',
    forms: 'Optik Formlar',
    form1: '26 Soru',
    form2: '60 Soru',
    google_drive: '(Google Drive)',
    see_all: 'Hepsini Gör',
    advertisements: 'Reklamlar',
    add_item: 'Ekle',
  },
  classes: {
    classes: 'Sınıflar',
    classes_capital: 'SINIFLAR',
    add_class: 'Sınıf Ekle',
    class_name: 'Sınıf Adı',
    class_name_required: 'Sınıf adı giriniz.',
    class_name_already_exists: 'Bu sınıf adı zaten kayıtlı.',
    class_name_cannot_be_edited: 'Bu sınıf adı değiştirilemez.',
    class_name_cannot_be_deleted: 'Bu sınıf adı silinemez.',
    class_name_cannot_be_empty: 'Sınıf adı boş olamaz.',
    search: 'Sınıf Ara',
    delete_all: 'Tümünü Sil',
    delete_all_warning: 'Geri alınamaz!',
    approve: 'Onayla',
    delete_class: 'Sınıfı Sil',
  },
  add_class: {
    add_class: 'Sınıf Ekle',
    class_name: 'Sınıf Adı',
    class_name_required: 'Sınıf adı boş olamaz.',
    class_name_already_exists: 'Bu sınıf adı zaten kayıtlı.',
  },
  edit_class: {
    edit_class: 'Sınıfı Düzenle',
    class_name: 'Sınıf Adı',
    class_name_required: 'Sınıf adı boş olamaz.',
    class_name_already_exists: 'Bu sınıf adı zaten kayıtlı.',
  },
  exams: {
    exams: 'Sınavlar',
    exams_capital: 'SINAVLAR',
    add_exam: 'Sınav Ekle',
    exam_name: 'Sınav Adı',
    exam_name_required: 'Sınav adı giriniz.',
    exam_name_already_exists: 'Bu sınav adı zaten kayıtlı.',
    exam_name_cannot_be_edited: 'Bu sınav adı değiştirilemez.',
    exam_name_cannot_be_deleted: 'Bu sınav adı silinemez.',
    exam_name_cannot_be_empty: 'Sınav adı boş olamaz.',
    exam_date: 'Sınav Tarihi',
    exam_date_required: 'Sınav tarihi giriniz.',
    exam_date_cannot_be_edited: 'Bu sınav tarihi değiştirilemez.',
    exam_number: 'Sınav sayısı',
    no_exams: 'Henüz sınav eklenmemiş.',
  },
}